FROM jcorioland/dotnet:windowsservercore-1.0.1

MAINTAINER Julien Corioland, Microsoft, @jcorioland

WORKDIR /app
ENTRYPOINT ["dotnet", "run"]
EXPOSE 5000
ENV ASPNETCORE_URLS http://+:5000

COPY . /app
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
